version: 0.2  
phases:  
  install:  
    runtime-versions:  
      python: 3.9  
  build:  
    commands:  
      - echo "Ejecutando pruebas"  
  post_build:  
    commands:  
      - echo "Construcción finalizada con éxito"
